version: '3'

services:
  bot:
    image: bot_image
    container_name: bot
    env_file:
      - '.env'
    networks:
      - nikita_net
    depends_on:
      - db

  db:
    image: db_image
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - '.env'
    networks:
      - nikita_net

  db_repl:
    image: db_repl_image
    container_name: db_repl
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - '.env'
    networks:
      - nikita_net
    depends_on:
      - db

networks:
  nikita_net:
    driver: bridge
